// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: admin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatusStatus int32

const (
	NodeStatus_HEALTHY NodeStatusStatus = 0
	NodeStatus_SICK    NodeStatusStatus = 1
	NodeStatus_QUITING NodeStatusStatus = 2
)

// Enum value maps for NodeStatusStatus.
var (
	NodeStatusStatus_name = map[int32]string{
		0: "HEALTHY",
		1: "SICK",
		2: "QUITING",
	}
	NodeStatusStatus_value = map[string]int32{
		"HEALTHY": 0,
		"SICK":    1,
		"QUITING": 2,
	}
)

func (x NodeStatusStatus) Enum() *NodeStatusStatus {
	p := new(NodeStatusStatus)
	*p = x
	return p
}

func (x NodeStatusStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatusStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[0].Descriptor()
}

func (NodeStatusStatus) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[0]
}

func (x NodeStatusStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatusStatus.Descriptor instead.
func (NodeStatusStatus) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0, 0}
}

type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

type RegistrationMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ServiceName string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	// id of instance this needs to be unique
	InstanceName string `protobuf:"bytes,2,opt,name=instanceName,proto3" json:"instanceName,omitempty"`
	// dial addr is what is passed back to the client to connect to
	DialAddr      string `protobuf:"bytes,3,opt,name=dialAddr,proto3" json:"dialAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationMessage) Reset() {
	*x = RegistrationMessage{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationMessage) ProtoMessage() {}

func (x *RegistrationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationMessage.ProtoReflect.Descriptor instead.
func (*RegistrationMessage) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationMessage) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegistrationMessage) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *RegistrationMessage) GetDialAddr() string {
	if x != nil {
		return x.DialAddr
	}
	return ""
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestTtl    int32                  `protobuf:"varint,1,opt,name=request_ttl,json=requestTtl,proto3" json:"request_ttl,omitempty"`
	SeqStart      int64                  `protobuf:"varint,2,opt,name=seqStart,proto3" json:"seqStart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RegistrationResponse) GetRequestTtl() int32 {
	if x != nil {
		return x.RequestTtl
	}
	return 0
}

func (x *RegistrationResponse) GetSeqStart() int64 {
	if x != nil {
		return x.SeqStart
	}
	return 0
}

type HeartBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNumber     int64                  `protobuf:"varint,1,opt,name=seqNumber,proto3" json:"seqNumber,omitempty"`
	InstanceName  string                 `protobuf:"bytes,2,opt,name=instanceName,proto3" json:"instanceName,omitempty"`
	Status        *NodeStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeat) Reset() {
	*x = HeartBeat{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeat) ProtoMessage() {}

func (x *HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeat.ProtoReflect.Descriptor instead.
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *HeartBeat) GetSeqNumber() int64 {
	if x != nil {
		return x.SeqNumber
	}
	return 0
}

func (x *HeartBeat) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *HeartBeat) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartBeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// echo back seqNumber to client
	Ack           int64 `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *HeartBeatResponse) GetAck() int64 {
	if x != nil {
		return x.Ack
	}
	return 0
}

type ServiceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceListRequest) Reset() {
	*x = ServiceListRequest{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceListRequest) ProtoMessage() {}

func (x *ServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceListRequest.ProtoReflect.Descriptor instead.
func (*ServiceListRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceListRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	InstanceName  string                 `protobuf:"bytes,2,opt,name=instanceName,proto3" json:"instanceName,omitempty"`
	DialAddr      string                 `protobuf:"bytes,3,opt,name=dialAddr,proto3" json:"dialAddr,omitempty"`
	LatestStatus  *NodeStatus            `protobuf:"bytes,4,opt,name=latestStatus,proto3" json:"latestStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInfo) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *ServiceInfo) GetDialAddr() string {
	if x != nil {
		return x.DialAddr
	}
	return ""
}

func (x *ServiceInfo) GetLatestStatus() *NodeStatus {
	if x != nil {
		return x.LatestStatus
	}
	return nil
}

type ServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*ServiceInfo         `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceListResponse) Reset() {
	*x = ServiceListResponse{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceListResponse) ProtoMessage() {}

func (x *ServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceListResponse.ProtoReflect.Descriptor instead.
func (*ServiceListResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceListResponse) GetInstances() []*ServiceInfo {
	if x != nil {
		return x.Instances
	}
	return nil
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\":\n" +
	"\n" +
	"nodeStatus\",\n" +
	"\x06status\x12\v\n" +
	"\aHEALTHY\x10\x00\x12\b\n" +
	"\x04SICK\x10\x01\x12\v\n" +
	"\aQUITING\x10\x02\"w\n" +
	"\x13registrationMessage\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\"\n" +
	"\finstanceName\x18\x02 \x01(\tR\finstanceName\x12\x1a\n" +
	"\bdialAddr\x18\x03 \x01(\tR\bdialAddr\"S\n" +
	"\x14registrationResponse\x12\x1f\n" +
	"\vrequest_ttl\x18\x01 \x01(\x05R\n" +
	"requestTtl\x12\x1a\n" +
	"\bseqStart\x18\x02 \x01(\x03R\bseqStart\"r\n" +
	"\tHeartBeat\x12\x1c\n" +
	"\tseqNumber\x18\x01 \x01(\x03R\tseqNumber\x12\"\n" +
	"\finstanceName\x18\x02 \x01(\tR\finstanceName\x12#\n" +
	"\x06status\x18\x03 \x01(\v2\v.nodeStatusR\x06status\"%\n" +
	"\x11HeartBeatResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\x03R\x03ack\"6\n" +
	"\x12serviceListRequest\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\"\xa0\x01\n" +
	"\vserviceInfo\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\"\n" +
	"\finstanceName\x18\x02 \x01(\tR\finstanceName\x12\x1a\n" +
	"\bdialAddr\x18\x03 \x01(\tR\bdialAddr\x12/\n" +
	"\flatestStatus\x18\x04 \x01(\v2\v.nodeStatusR\flatestStatus\"A\n" +
	"\x13serviceListResponse\x12*\n" +
	"\tinstances\x18\x01 \x03(\v2\f.serviceInfoR\tinstances2\xc4\x01\n" +
	"\tdiscovery\x12A\n" +
	"\x0fregisterService\x12\x14.registrationMessage\x1a\x16.google.protobuf.Empty\"\x00\x121\n" +
	"\theartbeat\x12\n" +
	".HeartBeat\x1a\x12.HeartBeatResponse\"\x00(\x010\x01\x12A\n" +
	"\x12requestServiceList\x12\x13.serviceListRequest\x1a\x14.serviceListResponse\"\x00B\x16Z\x14internal/proto;protob\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_admin_proto_goTypes = []any{
	(NodeStatusStatus)(0),        // 0: nodeStatus.status
	(*NodeStatus)(nil),           // 1: nodeStatus
	(*RegistrationMessage)(nil),  // 2: registrationMessage
	(*RegistrationResponse)(nil), // 3: registrationResponse
	(*HeartBeat)(nil),            // 4: HeartBeat
	(*HeartBeatResponse)(nil),    // 5: HeartBeatResponse
	(*ServiceListRequest)(nil),   // 6: serviceListRequest
	(*ServiceInfo)(nil),          // 7: serviceInfo
	(*ServiceListResponse)(nil),  // 8: serviceListResponse
	(*emptypb.Empty)(nil),        // 9: google.protobuf.Empty
}
var file_admin_proto_depIdxs = []int32{
	1, // 0: HeartBeat.status:type_name -> nodeStatus
	1, // 1: serviceInfo.latestStatus:type_name -> nodeStatus
	7, // 2: serviceListResponse.instances:type_name -> serviceInfo
	2, // 3: discovery.registerService:input_type -> registrationMessage
	4, // 4: discovery.heartbeat:input_type -> HeartBeat
	6, // 5: discovery.requestServiceList:input_type -> serviceListRequest
	9, // 6: discovery.registerService:output_type -> google.protobuf.Empty
	5, // 7: discovery.heartbeat:output_type -> HeartBeatResponse
	8, // 8: discovery.requestServiceList:output_type -> serviceListResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		EnumInfos:         file_admin_proto_enumTypes,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
