// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: storage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Empty_BlankRequest_FullMethodName = "/empty/blankRequest"
)

// EmptyClient is the client API for Empty service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmptyClient interface {
	BlankRequest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type emptyClient struct {
	cc grpc.ClientConnInterface
}

func NewEmptyClient(cc grpc.ClientConnInterface) EmptyClient {
	return &emptyClient{cc}
}

func (c *emptyClient) BlankRequest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Empty_BlankRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmptyServer is the server API for Empty service.
// All implementations must embed UnimplementedEmptyServer
// for forward compatibility.
type EmptyServer interface {
	BlankRequest(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedEmptyServer()
}

// UnimplementedEmptyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmptyServer struct{}

func (UnimplementedEmptyServer) BlankRequest(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlankRequest not implemented")
}
func (UnimplementedEmptyServer) mustEmbedUnimplementedEmptyServer() {}
func (UnimplementedEmptyServer) testEmbeddedByValue()               {}

// UnsafeEmptyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmptyServer will
// result in compilation errors.
type UnsafeEmptyServer interface {
	mustEmbedUnimplementedEmptyServer()
}

func RegisterEmptyServer(s grpc.ServiceRegistrar, srv EmptyServer) {
	// If the following call pancis, it indicates UnimplementedEmptyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Empty_ServiceDesc, srv)
}

func _Empty_BlankRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmptyServer).BlankRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Empty_BlankRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmptyServer).BlankRequest(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Empty_ServiceDesc is the grpc.ServiceDesc for Empty service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Empty_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "empty",
	HandlerType: (*EmptyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "blankRequest",
			Handler:    _Empty_BlankRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
