// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: storage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	URLStorage_PutURL_FullMethodName     = "/URLStorage/putURL"
	URLStorage_GetFullURL_FullMethodName = "/URLStorage/getFullURL"
)

// URLStorageClient is the client API for URLStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type URLStorageClient interface {
	PutURL(ctx context.Context, in *ShortURLRequest, opts ...grpc.CallOption) (*ShortUrlResponse, error)
	GetFullURL(ctx context.Context, in *FullUrlRequest, opts ...grpc.CallOption) (*FullUrlResponse, error)
}

type uRLStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewURLStorageClient(cc grpc.ClientConnInterface) URLStorageClient {
	return &uRLStorageClient{cc}
}

func (c *uRLStorageClient) PutURL(ctx context.Context, in *ShortURLRequest, opts ...grpc.CallOption) (*ShortUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortUrlResponse)
	err := c.cc.Invoke(ctx, URLStorage_PutURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLStorageClient) GetFullURL(ctx context.Context, in *FullUrlRequest, opts ...grpc.CallOption) (*FullUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FullUrlResponse)
	err := c.cc.Invoke(ctx, URLStorage_GetFullURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLStorageServer is the server API for URLStorage service.
// All implementations must embed UnimplementedURLStorageServer
// for forward compatibility.
type URLStorageServer interface {
	PutURL(context.Context, *ShortURLRequest) (*ShortUrlResponse, error)
	GetFullURL(context.Context, *FullUrlRequest) (*FullUrlResponse, error)
	mustEmbedUnimplementedURLStorageServer()
}

// UnimplementedURLStorageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedURLStorageServer struct{}

func (UnimplementedURLStorageServer) PutURL(context.Context, *ShortURLRequest) (*ShortUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutURL not implemented")
}
func (UnimplementedURLStorageServer) GetFullURL(context.Context, *FullUrlRequest) (*FullUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullURL not implemented")
}
func (UnimplementedURLStorageServer) mustEmbedUnimplementedURLStorageServer() {}
func (UnimplementedURLStorageServer) testEmbeddedByValue()                    {}

// UnsafeURLStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to URLStorageServer will
// result in compilation errors.
type UnsafeURLStorageServer interface {
	mustEmbedUnimplementedURLStorageServer()
}

func RegisterURLStorageServer(s grpc.ServiceRegistrar, srv URLStorageServer) {
	// If the following call pancis, it indicates UnimplementedURLStorageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&URLStorage_ServiceDesc, srv)
}

func _URLStorage_PutURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLStorageServer).PutURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLStorage_PutURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLStorageServer).PutURL(ctx, req.(*ShortURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLStorage_GetFullURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLStorageServer).GetFullURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLStorage_GetFullURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLStorageServer).GetFullURL(ctx, req.(*FullUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// URLStorage_ServiceDesc is the grpc.ServiceDesc for URLStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var URLStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "URLStorage",
	HandlerType: (*URLStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "putURL",
			Handler:    _URLStorage_PutURL_Handler,
		},
		{
			MethodName: "getFullURL",
			Handler:    _URLStorage_GetFullURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
