openapi: 3.0.0
info:
  title: Admin Service API
  version: 1.0.1
  description: API for updating configuration and monitoring the health of services.
servers:
  - url: https://{hostname}/api_admin/
    variables:
      hostname:
        default: localhost
paths:
  /getServices:
    get:
      summary: Get all registered services
      operationId: getServices
      responses:
        '200':
          description: List of registered services
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
        401:
          description: Must be Signed in to do this operation
        403:
          description: Must be an Admin to do this

  /removeService:
    delete:
      summary: Remove an existing service
      operationId: removeService
      parameters:
        - name: id
          in: query
          description: ID of the service to remove
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Service removed successfully
        '404':
          description: Service not found
        401:
          description: Must be Signed In
        403:
          description: Must be an Admin to do this operation

  /health:
    get:
      summary: Check service health
      operationId: checkHealth
      parameters:
        - name: id
          in: query
          description: ID of service to get health for (optional)
          required: true
          schema:
            type: string
        - name: serviceName
          in: query
          description: ServiceName where the service is apart of
          required: true
      responses:
        '200':
          description: Health information
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ServiceHealth'
                  - type: array
                    items:
                      $ref: '#/components/schemas/ServiceHealth'
        '404':
          description: Unable to find service under that name
        '401':
          description: Requires login
        '403':
          description: Must be Admin to check this

components:
  securitySchemes:
    keycloakOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://keycloak.example.com/realms/gominify/protocol/openid-connect/auth
          tokenUrl: https://keycloak.example.com/realms/gominify/protocol/openid-connect/token
          scopes:
            openid: OpenID Connect basic authentication
            admin: Admin scope for interacting with admin panel

  schemas:
    Service:
      type: object
      required:
        - id
        - name
        - url
        - leaseInformation
      properties:
        id:
          type: string
          example: service-123
        name:
          type: string
          example: storage-service
        url:
          type: string
          format: uri
          example: http://storage.internal:8080
        leaseInformation:
          type: string
          format: date-time

    ServiceHealth:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [healthy, sick, quiting]
        lastChecked:
          type: string
          format: date-time

security:
  - keycloakOAuth: [openid, admin]