openapi: 3.0.0
info:
  title: GoMinifyURL Shorter API
  version: 1.0.1
  description: |
    A minimal URL shortening service. Uses Keycloak for authentication.

servers:
  - url: https://{hostname}/go
    variables:
      hostname:
        default: localhost

paths:
  /shrink:
    post:
      summary: Shorten a URL
      description: Authenticated users can shorten a long URL.
      operationId: shrinkUrl
      security:
        - keycloakOAuth: [openid,url:write]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [url]
              properties:
                url:
                  type: string
                  format: uri
      responses:
        '200':
          description: Shortened URL created
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
        '401':
          description: Unauthorized
        '400':
          description: Invalid input

  /{url}:
    get:
      summary: Redirect to long URL
      security: []
      description: Public endpoint that redirects users from a short slug.
      operationId: redirect
      parameters:
        - in: path
          name: url
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect to original URL
        '404':
          description: Not found

components:
  securitySchemes:
    keycloakOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://keycloak.example.com/realms/gominifyurl/protocol/openid-connect/auth
          tokenUrl: https://keycloak.example.com/realms/gominifyurl/protocol/openid-connect/token
          scopes:
            openid: Access your identity
            url:write: Ability to put urls into system

security:
  - keycloakOAuth: [openid]
