//go:build go1.22

// Package analytics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package analytics

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	KeycloakOAuthScopes = "keycloakOAuth.Scopes"
)

// GetUserTopUrlsParams defines parameters for GetUserTopUrls.
type GetUserTopUrlsParams struct {
	// Limit Number of top URLs to return (default: 10, max: 20)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get information about entire system this path does not require oauth
	// (GET /general)
	GetGeneral(w http.ResponseWriter, r *http.Request)
	// Get detailed analytics for a shortened URL
	// (GET /url/{shortId}/stats)
	GetDetailedUrlStats(w http.ResponseWriter, r *http.Request, shortId string)
	// Get country-level click summary for authenticated user's links
	// (GET /user/geo)
	GetUserGeoSummary(w http.ResponseWriter, r *http.Request)
	// Get referral graph for authenticated user's short URLs
	// (GET /user/referrals)
	GetUserReferralGraph(w http.ResponseWriter, r *http.Request)
	// Get top K most-clicked short URLs for the authenticated user
	// (GET /user/top)
	GetUserTopUrls(w http.ResponseWriter, r *http.Request, params GetUserTopUrlsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetGeneral operation middleware
func (siw *ServerInterfaceWrapper) GetGeneral(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGeneral(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDetailedUrlStats operation middleware
func (siw *ServerInterfaceWrapper) GetDetailedUrlStats(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shortId" -------------
	var shortId string

	err = runtime.BindStyledParameterWithOptions("simple", "shortId", r.PathValue("shortId"), &shortId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shortId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, KeycloakOAuthScopes, []string{"openid", "analytics:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDetailedUrlStats(w, r, shortId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserGeoSummary operation middleware
func (siw *ServerInterfaceWrapper) GetUserGeoSummary(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, KeycloakOAuthScopes, []string{"openid", "analytics:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserGeoSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserReferralGraph operation middleware
func (siw *ServerInterfaceWrapper) GetUserReferralGraph(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, KeycloakOAuthScopes, []string{"openid", "analytics:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserReferralGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserTopUrls operation middleware
func (siw *ServerInterfaceWrapper) GetUserTopUrls(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, KeycloakOAuthScopes, []string{"openid", "analytics:read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserTopUrlsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserTopUrls(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/general", wrapper.GetGeneral)
	m.HandleFunc("GET "+options.BaseURL+"/url/{shortId}/stats", wrapper.GetDetailedUrlStats)
	m.HandleFunc("GET "+options.BaseURL+"/user/geo", wrapper.GetUserGeoSummary)
	m.HandleFunc("GET "+options.BaseURL+"/user/referrals", wrapper.GetUserReferralGraph)
	m.HandleFunc("GET "+options.BaseURL+"/user/top", wrapper.GetUserTopUrls)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RY3W4buxF+lQFv6gBrreQEudBd6rSGkbQu7PiiiIOG4o60jLkkQ87aUQwBveoD9Lxh",
	"nuRgyF39WJLjk/ggV5Z2yZlvZr5vZuQ7oVzjnUVLUYzvRETVBk3zC1Vjg+nRNc6VcfL67FVLNT+YGneb",
	"3siWahf0V0na2WNX4dbDy2DEWNREPo7Lsrc0wC+y8QYHyjVlQGmaWM5co62ezksfHDnlTOk8Wl0dKmct",
	"KirZrihEVM5nXNJKMyet4jigrMRYnKOswGNoIrgpUI2wPAIRww0GUYhsVYzFmUd7+hqOs3mYyKgVsBO0",
	"pFVCLxaFIHeNTxlGsicWbHnuUYyFY59HYsGPtJ06Dq3CqIL2CcNYvFpGIb2GqQtw4v6RvFyevx3AZcQI",
	"b3B+zJjS6y5VpMmwh7XTaxl59a9TUYgbDDF7GQ2GgxFHzICl12Isng+Gg6EohJdUp5SXM7QYpOHPMyT+",
	"4zyGlKxTTuoJ0kl3pBABo3c25modDYf8RzlLaNNN6b3pEl1+iozhTkSmneRPPrBl0vk2OZLmrbbXcTs9",
	"tm0mGLjk6QBQLQlqeYMwQbQQaxcILVZimfJ8I1eXpDnHSgdUtMP2P5e2Q38oE8t7qGUEH5zCGLECd4MB",
	"NEUweoqkG9zlro0YHowgHYCAMx0Jwy7Ma8SZfEJFmTib9roqAdMpNCnDICeuJajdLTTSzrOjAgxnrABp",
	"q1WAyUdsm0aGeS7pDkMskoAQ55GwAap1BGYJVA4jWEcQ8HPLJxK9k8myDaa8S+U4rRZlJJkz3hFpM4Rz",
	"pDbYCDN0HbopBo5pElBeV+7Wxkx1iNrODOYyAwviyp5ZMwepuDJ6YhAm81Q0d2tzlvlLPpkbwiaBXyNJ",
	"bbC6DOYiYWQBBNkgpeK9vxOaEXK4ohBWNlyMLqzE+hR4JcYUWizWKN3VLVLQdiYWiw9PKhFltLqOf50f",
	"u9YSV+5OaMIm7jjJJ9YAaUs4ywRVq8v30W7xbvlAhiDn/L0vUvwx5/k6hh/03pdg+3an8+OUoV2+HyOq",
	"nharFsqGXwxH2+S9tP0QxCofer596O8uTHRVoYVv//0t6XElHndre5KCC9zh80tL6XWeceT41n04L3bA",
	"OX+brk1da6us7m7KJzbfm+/v+xFZ3J+wH5ixm42h2kpKr8q+63IMnfwjhnKG7rualyuRs1oTsSHxJrKU",
	"O46CVMHFCNKYXtPs4S9x03ccXNnLiNPWJGQ3OrbS6K/azkC2lUarEIzLGoMDHMwGBdQoqZGeU+81gqpl",
	"oGd7ugXX5gTdRZeWn5T090Szbzpl8cM0uK4Z90IuHhb5pr13t+7QIBGGZZKVqxAOTi/O4Pno5cvDEUjj",
	"a3l49Gxl+fEa3RZV16wODd6g6SrdM+xx6npKNqv9aJZ7VbcdYtWzLY3QNYZvNMHv8HwWpK/zdpFbH3z7",
	"3/9XowwCmsSUWGuflcU0V20IaGkDwODK/k2qGphAoG2VMMZ7857Zrxm6hJm+6XejZCBTR0L0qPRUqyWi",
	"B2h/3kV6wlH82cz/Q+PioWHwIzTtI+0KVkmSv4CeYRPFXkYu+bNOS3L+EYQM0l5jBUZHWv6G2uWicZEO",
	"k0CwWvM3uLL/di0oaTsizVcMJAch+YGWV7Zk+6PRjaaPsNyv4KCRX3TTNmM4Gj7Uct85fxnMjt1sX4ck",
	"5xPENRwHFU5la2gMo2EBjfySnCafacP73GLqoN2Kl7CK9YWuuy/Go2EhOuBifMRftM1fRtsN+Kf3vn1S",
	"4XIc79fL00rinfPwJq8tKa08mFeD+heogxKgPcRc9s5tNufg8v8HMoXajV/7d7WLxBRYlNLr/yyBlPzr",
	"WQYtJybnvz+3wQzBu4XhV+znw+L3AAAA//+UDUFUcBEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
