//go:build go1.22

// Package analytics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package analytics

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	KeycloakOAuthScopes = "keycloakOAuth.Scopes"
)

// GetUserTopUrlsParams defines parameters for GetUserTopUrls.
type GetUserTopUrlsParams struct {
	// Limit Number of top URLs to return (default: 10, max: 20)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get detailed analytics for a shortened URL
	// (GET /url/{shortId}/stats)
	GetDetailedUrlStats(w http.ResponseWriter, r *http.Request, shortId string)
	// Get country-level click summary for authenticated user's links
	// (GET /user/geo)
	GetUserGeoSummary(w http.ResponseWriter, r *http.Request)
	// Get referral graph for authenticated user's short URLs
	// (GET /user/referrals)
	GetUserReferralGraph(w http.ResponseWriter, r *http.Request)
	// Get top K most-clicked short URLs for the authenticated user
	// (GET /user/top)
	GetUserTopUrls(w http.ResponseWriter, r *http.Request, params GetUserTopUrlsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDetailedUrlStats operation middleware
func (siw *ServerInterfaceWrapper) GetDetailedUrlStats(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shortId" -------------
	var shortId string

	err = runtime.BindStyledParameterWithOptions("simple", "shortId", r.PathValue("shortId"), &shortId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shortId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, KeycloakOAuthScopes, []string{"openid"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDetailedUrlStats(w, r, shortId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserGeoSummary operation middleware
func (siw *ServerInterfaceWrapper) GetUserGeoSummary(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, KeycloakOAuthScopes, []string{"openid"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserGeoSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserReferralGraph operation middleware
func (siw *ServerInterfaceWrapper) GetUserReferralGraph(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, KeycloakOAuthScopes, []string{"openid"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserReferralGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserTopUrls operation middleware
func (siw *ServerInterfaceWrapper) GetUserTopUrls(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, KeycloakOAuthScopes, []string{"openid"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserTopUrlsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserTopUrls(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/url/{shortId}/stats", wrapper.GetDetailedUrlStats)
	m.HandleFunc("GET "+options.BaseURL+"/user/geo", wrapper.GetUserGeoSummary)
	m.HandleFunc("GET "+options.BaseURL+"/user/referrals", wrapper.GetUserReferralGraph)
	m.HandleFunc("GET "+options.BaseURL+"/user/top", wrapper.GetUserTopUrls)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RX3W7bOBN9lQFvvhRwLDsteqG7fuluELS7WST1xaIpUJoaW6wpkiVHSVXDwF7tA+y+",
	"YZ9kMZTknzpOf3NliBrOnJk5ZzReCuUq7yxaiiJfioiqDpqaK1VihelogY0yTi4untVU8sHMuNv0RtZU",
	"uqA/StLOnroC9w4nwYhclEQ+5lnWexriB1l5g0PlqiygNFXM5q7SVs+azAdHTjmTOY9WF8fKWYuKMvYr",
	"BiIq51tc7XuRiwuP9vw5nLaGMJVRK2BztKRVwiFWA0FugT8TUPInVuy58Shy4TjmiVjxkbYzxyALjCpo",
	"nzDk4pmVpiGtIkivYeYCnLnfUpTJ5cshTCJGeIHNKWNKr7ukSZPhCFvWINe+nv1xLgbiBkNso4yHo+GI",
	"M2bA0muRi8fpaCC8pDIVL6uDyZaxdIHOi1UWSbb9nyPtw75EqoONMEcH0hYQcIYhSAPTgHJRuFsbW7QQ",
	"tZ0bhOQXOKdre2FNA1IpjFFPDcK0ASoR3K3FAG6WHlpLkRCH1LBzbuwZ0nMkqQ0Wk2CuEkbOIcgKCUMU",
	"+eul0IyQ8xIDYWXFZerSEgMR8H2tAxYip1Ajs6fESnKGXc8iBW3nYrV6w8bROxtbdp2MRvyjnCW0qSbS",
	"e9PRKXsXuTDLLX8+MHbS7W1ltFrE/zenrrYUGj7ShFW8w5IttgBpSzjHwO1Tm8ufo91wbvoOFYnNgQxB",
	"NvzcNyl+X/D2OobvjN63YP82C5GkOU0Vuiv2vns+2mVkT4uNCtjxk9F4n7wT208kLFqjx/tGv7ow1UWB",
	"Fj799S/UEQMUDiNYR8zUnqTt/Sd3BLl8mWxnrrZFSqEfpImjn43Q1/3sesO0i3VVSW4z8x2Kvcx6aXFF",
	"0WLRAlkNRMY4szm6LwpXbpTKkkvshNT8yHrsiAZSBRcjSGN6YXKE/8Xd2HF4bScRZ7VJyG50rKXRH7Wd",
	"g6wLjVYhGNcKBY5wOB8OoERJlfTgAniNoEoZ6NEByU8ihjN0V11ZflCXX2L+bsF+r6tpO5ZaBcMsuAqo",
	"1LEvkhjcr9Rdf69u3bFBIgzrIitXIBydX13A4/HTp8djkMaX8vjk0cbz1wttXxndxDk2eIOm63TPsK+T",
	"yA+QVx0Ovv6cdR9lLHpyGW0XcYvQO4PrC7SeB+lLblc/ruDT3/9sPj8Q0CRixFL7VkjMalWHgJZ2AAyv",
	"7S9SlcB8AW2LhDFC6W6hkrZJtpHJrhm6hLm+QdtFYgctUyREj0rPtFojuofll12mZ5zFQxP9m0b8fQP8",
	"e1jZZ9o1rJAkH56NYTfoQQKu6bLNQnL+K/gXpF1gAUZH6kfmnSEqF+k46QGLrXjDa/unq0FJ2/Gm2RCO",
	"HIQUB2reqpLvt0ZXmt7CegWCo0p+0FVd5XAyum+gvnJ+Eswd69Oh+UfOJ4hbOI4KnMnaUA7j0QAq+SEF",
	"TTHTEva+xjQfuy0sYRXbO1d3X+Tj0UB0wEV+wg/atg/j/fH6w6vZIWVwO04Py+PnKuCV8/Ci3SxSWfmz",
	"u/kMP7wYKMU/wMP1ZNwnb5vLN0TFcNNzq975s7UsXSTmxipb7zYZ/3GRQcupaZvS2+zQRfA6YfgVo3mz",
	"+i8AAP//cRGVhbUOAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
